version: "3"
volumes:
  pgdata:
services:
  db:
    image: docker.io/postgres:14
    environment:
      POSTGRES_PASSWORD: smolshot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
